version: 2
jobs:
  build:
    macos:
      xcode: "10.0.0"
    working_directory: ~/sora-ios-sdk
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run:
          name: Install Carthage
          command: carthage update --platform iOS

      - run:
          name: Build
          command: |
            set -o pipefail && \
            xcodebuild \
              -project 'SoraQuickStart.xcodeproj' \
              -scheme 'SoraQuickStart' \
              clean build \
              -sdk iphoneos \
              -destination 'generic/platform=iOS' \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGN_IDENTITY= \
              PROVISIONING_PROFILE= | \
            tee $CIRCLE_ARTIFACTS/xcode_raw.log | \
            xcpretty --color --report junit --output $CIRCLE_TEST_REPORTS/xcode/results.xml

workflows:
  version: 2
  build-and-test:
    jobs:
      - build

