source 'https://cdn.cocoapods.org/'
source 'https://github.com/shiguredo/sora-ios-sdk-specs.git'

platform :ios, '13.0'

target 'SoraQuickStart' do
  use_frameworks!
  pod 'Sora', :git => 'https://github.com/shiguredo/sora-ios-sdk.git', :branch => 'feature/swiftui'

  pod 'SwiftLint'
  pod 'SwiftFormat/CLI'

end
